FROM python:3.13-slim AS base

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends postgresql-client \
 && rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt


FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends postgresql-client \
 && apt-get install -y ffmpeg \
 && rm -rf /var/lib/apt/lists/*

COPY --from=base /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY scripts /scripts
RUN chmod +x /scripts/entrypoint-dev.sh

# create non-root user
RUN addgroup --system app && adduser --system --ingroup app app
RUN chown -R app:app /app

USER app

COPY . .

EXPOSE 8000

ENTRYPOINT ["/scripts/entrypoint-dev.sh"]
# no reload in prod
CMD ["faststream", "run", "app.main:app", "--reload"]


