services:
  auth-service:
    build: ./auth-service
    env_file:
      - .env.root
      - .env.auth
    environment:
      - ENVIRONMENT=production

  upload-service:
    build: ./upload-service
    env_file:
      - .env.root
      - .env.upload


  minio:
    image: minio/minio:latest
    container_name: nebori_minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.root
    ports:
      - "9000:9000"  # Main port for API
      - "9001:9001"  # Admin port
    volumes:
      - minio_data:/data

volumes:
  minio_data: