services:
  auth:
    build: ./services/auth
    container_name: nebori_auth
    env_file:
      - .env.dev.root
      - .env.dev.auth
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8104:8000"
    networks:
      - nebori-network

  user:
    build: ./services/user
    container_name: nebori_user
    env_file:
      - .env.dev.root
      - .env.dev.user
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASS: ${RABBITMQ_PASS}
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8105:8000"
    volumes:
      - user_media:/app/media
    networks:
      - nebori-network

  db:
    image: postgres:16-alpine
    container_name: nebori_db
    env_file:
      - .env.dev.root
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./infra/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5434:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'",
        ]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - nebori-network

  upload:
    build:
      context: ./services/upload
      dockerfile: Dockerfile.dev
    container_name: nebori-upload-serv
    env_file:
      - .env.dev.root
      - .env.dev.upload
    ports:
      - "8101:8000"
    volumes:
      - ./services/upload:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: /app/scripts/entrypoint-dev.sh
    # БЕЗ --reload щоб lifespan (broker.start) відпрацьовував стабільно
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - nebori-network

  transcoding:
    build:
      context: ./services/transcoding
      dockerfile: Dockerfile.dev
    container_name: nebori-transcoding-serv
    env_file:
      - .env.dev.root
      - .env.dev.transcoding
    ports:
      - "8102:8000"
    volumes:
      - ./services/transcoding:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: /app/scripts/entrypoint-dev.sh
    command: faststream run app.main:app --reload
    networks:
      - nebori-network

  metadata:
    build:
      context: ./services/video_metadata
      dockerfile: Dockerfile.dev
    container_name: nebori-video_metadata-serv
    env_file:
      - .env.dev.root
      - .env.dev.video_metadata
    ports:
      - "8103:8000"
    volumes:
      - ./services/video_metadata:/app
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    entrypoint: /app/scripts/entrypoint-dev.sh
    # БЕЗ --reload щоб lifespan (broker.start) відпрацьовував стабільно
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - nebori-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: nebori_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - nebori-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: nebori-rabbitmq
    env_file:
      - .env.dev.root
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nebori-network
  nginx:
    image: nginx:alpine
    container_name: nebori-nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - upload
      - metadata
      - auth
      - user
      - minio
    networks:
      - nebori-network
  minio:
    image: minio/minio:latest
    container_name: nebori-minio
    command: server /data --console-address ":9001"
    env_file:
      - .env.dev.root
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - nebori-network

networks:
  nebori-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data:
  user_media:
  rabbitmq_data:
