services:
  # auth-service:
  #   build: ./auth-service
  #   env_file:
  #     - .env.shared
  #     - .env.auth
  #   environment:
  #     - ENVIRONMENT=production

  # upload-service:
  #   build: ./upload-service
  #   env_file:
  #     - .env.shared
  #     - .env.upload


  minio:
    image: minio/minio:latest
    container_name: nebori_minio
    # Запускаємо сервер і вказуємо порт для адмінки (9001)
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # Головний порт для API (сюди буде стукати FastAPI)
      - "9001:9001"  # Порт для веб-адмінки (сюди будеш заходити ти через браузер)
    environment:
      MINIO_ROOT_USER: admin           # Твій Access Key (Логін)
      MINIO_ROOT_PASSWORD: password123 # Твій Secret Key (Пароль)
    volumes:
      - minio_data:/data  # Зберігаємо дані на диску, щоб вони не зникли після рестарту

volumes:
  minio_data: # Оголошуємо volume