"""

Revision ID: 7128f72de8d2
Revises: 855744e567c6
Create Date: 2026-05-08 14:48:32.252362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7128f72de8d2'
down_revision: Union[str, Sequence[str], None] = '855744e567c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'user_id')
    op.add_column('videos', sa.Column('user_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
