"""

Revision ID: 96f6cf8db9fa
Revises: 7128f72de8d2
Create Date: 2026-05-08 17:55:15.694955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f6cf8db9fa'
down_revision: Union[str, Sequence[str], None] = '7128f72de8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_hls_urls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('video_id', sa.Uuid(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_hls_urls_video_id'), 'video_hls_urls', ['video_id'], unique=False)
    op.create_index(op.f('ix_videos_user_id'), 'videos', ['user_id'], unique=False)
    op.drop_column('videos', 'playlist_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('playlist_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_videos_user_id'), table_name='videos')
    op.drop_index(op.f('ix_video_hls_urls_video_id'), table_name='video_hls_urls')
    op.drop_table('video_hls_urls')
    # ### end Alembic commands ###
