"""

Revision ID: 6a177b88e868
Revises: 82ce4c4592aa
Create Date: 2026-05-08 16:16:57.705708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a177b88e868'
down_revision: Union[str, Sequence[str], None] = '82ce4c4592aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_uploads', 'user_id')
    op.add_column('video_uploads', sa.Column('user_id', sa.Integer(), nullable=False, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_uploads', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
