"""update video_uploads table

Revision ID: c3508652ec2c
Revises: 9b31e890b788
Create Date: 2026-05-02 16:08:49.467961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3508652ec2c'
down_revision: Union[str, Sequence[str], None] = '9b31e890b788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_uploads', sa.Column('video_id', sa.UUID(), nullable=False))
    op.add_column('video_uploads', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('video_uploads', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('pending', 'processing', 'ready', 'failed', name='videostatusenum', native_enum=False),
               existing_nullable=False)
    op.create_index(op.f('ix_video_uploads_user_id'), 'video_uploads', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_uploads_video_id'), 'video_uploads', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_uploads_video_id'), table_name='video_uploads')
    op.drop_index(op.f('ix_video_uploads_user_id'), table_name='video_uploads')
    op.alter_column('video_uploads', 'status',
               existing_type=sa.Enum('pending', 'processing', 'ready', 'failed', name='videostatusenum', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('video_uploads', 'user_id')
    op.drop_column('video_uploads', 'video_id')
    # ### end Alembic commands ###
