"""add video_uploads table

Revision ID: 9b31e890b788
Revises: f8ee62cd78ca
Create Date: 2026-05-02 15:44:20.560544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b31e890b788'
down_revision: Union[str, Sequence[str], None] = 'f8ee62cd78ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_uploads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_path', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_uploads_id'), 'video_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_video_uploads_status'), 'video_uploads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_uploads_status'), table_name='video_uploads')
    op.drop_index(op.f('ix_video_uploads_id'), table_name='video_uploads')
    op.drop_table('video_uploads')
    # ### end Alembic commands ###
